// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtdwgpqfratkepiwtmud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0ZHdncHFmcmF0a2VwaXd0bXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzE4NzksImV4cCI6MjA2MDgwNzg3OX0.eY_VaaYfTewVItYmEfmyxO8FIJf256BfibTR5TBvQ24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);